export default {
  FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCTS_REQUEST',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',

  SET_TEXT: 'SET_TEXT',
  SET_TEXT_CONFIRM: 'SET_TEXT_CONFIRM',
};
